<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nihad Alili (466258) &amp; Vikram Bahadur (4666547)">
<meta name="dcterms.date" content="2025-01-25">

<title>Quantitative strategies on High Frequency Data - 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="presentation_hft_2025_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation_hft_2025_files/libs/quarto-html/quarto.js"></script>
<script src="presentation_hft_2025_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation_hft_2025_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="presentation_hft_2025_files/libs/quarto-html/anchor.min.js"></script>
<link href="presentation_hft_2025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation_hft_2025_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="presentation_hft_2025_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="presentation_hft_2025_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="presentation_hft_2025_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">sandstone</h2>
   
  <ul>
  <li><a href="#group-1---final-strategy---pair-trading" id="toc-group-1---final-strategy---pair-trading" class="nav-link active" data-scroll-target="#group-1---final-strategy---pair-trading">Group 1 - Final Strategy - Pair Trading</a></li>
  <li><a href="#group-1---2022-2024-quarterly-results-in-sample-data" id="toc-group-1---2022-2024-quarterly-results-in-sample-data" class="nav-link" data-scroll-target="#group-1---2022-2024-quarterly-results-in-sample-data">Group 1 - 2022-2024 quarterly results (In sample data)</a></li>
  <li><a href="#group-1---2022-2024-quarterly-results-out-sample-data" id="toc-group-1---2022-2024-quarterly-results-out-sample-data" class="nav-link" data-scroll-target="#group-1---2022-2024-quarterly-results-out-sample-data">Group 1 - 2022-2024 quarterly results (Out sample data)</a></li>
  <li><a href="#approaches-undertaken" id="toc-approaches-undertaken" class="nav-link" data-scroll-target="#approaches-undertaken">Approaches undertaken</a>
  <ul class="collapse">
  <li><a href="#group-2" id="toc-group-2" class="nav-link" data-scroll-target="#group-2">Group 2</a></li>
  </ul></li>
  <li><a href="#assumptions-1" id="toc-assumptions-1" class="nav-link" data-scroll-target="#assumptions-1">Assumptions:</a>
  <ul class="collapse">
  <li><a href="#group-2--2022-first-quarter-results" id="toc-group-2--2022-first-quarter-results" class="nav-link" data-scroll-target="#group-2--2022-first-quarter-results">Group 2- 2022 first quarter results</a></li>
  <li><a href="#group-2---2022-third-quarter-results" id="toc-group-2---2022-third-quarter-results" class="nav-link" data-scroll-target="#group-2---2022-third-quarter-results">Group 2 - 2022 third quarter results</a></li>
  <li><a href="#group-2---2022-fourth-quarter-results" id="toc-group-2---2022-fourth-quarter-results" class="nav-link" data-scroll-target="#group-2---2022-fourth-quarter-results">Group 2 - 2022 fourth quarter results</a></li>
  <li><a href="#group-2---2023-second-quarter-results" id="toc-group-2---2023-second-quarter-results" class="nav-link" data-scroll-target="#group-2---2023-second-quarter-results">Group 2 - 2023 Second quarter results</a></li>
  <li><a href="#group-2---2023-fourth-quarter-results" id="toc-group-2---2023-fourth-quarter-results" class="nav-link" data-scroll-target="#group-2---2023-fourth-quarter-results">Group 2 - 2023 Fourth quarter results</a></li>
  <li><a href="#group-2---2024-first-quarter-results" id="toc-group-2---2024-first-quarter-results" class="nav-link" data-scroll-target="#group-2---2024-first-quarter-results">Group 2 - 2024 First quarter results</a></li>
  <li><a href="#group-2---2024-second-quarter-results" id="toc-group-2---2024-second-quarter-results" class="nav-link" data-scroll-target="#group-2---2024-second-quarter-results">Group 2 - 2024 Second quarter results</a></li>
  </ul></li>
  <li><a href="#group-2---2022-2024-quarterly-results" id="toc-group-2---2022-2024-quarterly-results" class="nav-link" data-scroll-target="#group-2---2022-2024-quarterly-results">Group 2 - 2022-2024 quarterly results</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#group-2---out-of-sample-data-strategy-checking" id="toc-group-2---out-of-sample-data-strategy-checking" class="nav-link" data-scroll-target="#group-2---out-of-sample-data-strategy-checking">Group 2 - out of sample data, strategy checking</a>
  <ul class="collapse">
  <li><a href="#goup-2---2022-second-quarter-results" id="toc-goup-2---2022-second-quarter-results" class="nav-link" data-scroll-target="#goup-2---2022-second-quarter-results">Goup 2 - 2022 second quarter results</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#group-2---2023-first-quarter-results" id="toc-group-2---2023-first-quarter-results" class="nav-link" data-scroll-target="#group-2---2023-first-quarter-results">Group 2 - 2023 first quarter results</a></li>
  <li><a href="#group-2---2023-third-quarter" id="toc-group-2---2023-third-quarter" class="nav-link" data-scroll-target="#group-2---2023-third-quarter">Group 2 - 2023 third quarter</a></li>
  <li><a href="#group-2---2024-third-quarter" id="toc-group-2---2024-third-quarter" class="nav-link" data-scroll-target="#group-2---2024-third-quarter">Group 2 - 2024 third quarter</a></li>
  <li><a href="#group-2---2024-fourth-quarter" id="toc-group-2---2024-fourth-quarter" class="nav-link" data-scroll-target="#group-2---2024-fourth-quarter">Group 2 - 2024 fourth quarter</a></li>
  <li><a href="#group-2---summary" id="toc-group-2---summary" class="nav-link" data-scroll-target="#group-2---summary">Group 2 - Summary</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Quantitative strategies on High Frequency Data - 2025</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nihad Alili (466258) &amp; Vikram Bahadur (4666547) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 25, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="group-1---final-strategy---pair-trading" class="level3">
<h3 class="anchored" data-anchor-id="group-1---final-strategy---pair-trading">Group 1 - Final Strategy - Pair Trading</h3>
<p>Considering the NASDAQ index future price and S&amp;P 500 index future price represent the same returns on short/long run. If there is any change it should be temporary and should return back to earlier spread. So pair tradindin with mean reverting looks promising.</p>
<p>We used mean reverting pair trading using previous day average closing price ratio based spread and sds (standard deviation) ratios of returns based spread. Initially we tried different combination of entry/exit parameters and found that parameters those fit very well for particular dataset does not mean to fit significantly for the different data set. This because of changes in trends/patterns between data due to course of time. So we decided to find the best parameters on weekly basis and use them to run the pair strategy for next week. So technically every weeks parameters shifted to next week. Therefore for any given data set pre condition becomes it must be more than one week and ultimately we don’t trade at all the very first week of any given trade.</p>
<section id="assumptions" class="level4">
<h4 class="anchored" data-anchor-id="assumptions"><strong>Assumptions</strong></h4>
<ul>
<li><p><strong>do not trade</strong> first week of every quarter</p></li>
<li><p><strong>do not use in calculations</strong>&nbsp;the data from the first and last 10 minutes of the session (<code>9:31-9:40</code>&nbsp;and&nbsp;<code>15:51-16:00</code>)</p></li>
<li><p>do not hold positions overnight (<strong>exit all positions</strong>&nbsp;20 minutes before the session end, i.e.&nbsp;at&nbsp;<code>15:40</code>),</p></li>
<li><p><strong>do not trade</strong>&nbsp;within the first 25 minutes of stocks quotations (<code>9:31-9:55</code>), but&nbsp;<strong>DO use</strong>&nbsp;the data for&nbsp;<code>9:41-9:55</code>&nbsp;in calculations of signal, volatility, etc.</p></li>
</ul>
</section>
<section id="parameters-are" class="level4">
<h4 class="anchored" data-anchor-id="parameters-are"><strong>Parameters are</strong></h4>
<ul>
<li><p>spread.name = 1 (average mean ratio based spread) or 2 (sd ratio based spread).</p></li>
<li><p>net.SR = net sharpe ratio based on net pnl.</p></li>
<li><p>m = multipler to form upper and lower limits of signal.</p></li>
<li><p>volat.sd = rolling volatility of spread based on 60, 90, 120, 150 or 180 minutes data.</p></li>
</ul>
<p>We calculated these parameters on daily basis and analysis them weekly basis to select the best one as per maximum net SR ratio and saved every Friday. Further we moved these parameters to next week Monday morning and filled the whole week as minute data.</p>
<p>Sample parameters from 2024 Quarter 2 (in sample data) looks like</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/best_parameters_2024_q2.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">best_parameters_2024_q2</figcaption>
</figure>
</div>
</section>
<section id="entryexit-technique" class="level4">
<h4 class="anchored" data-anchor-id="entryexit-technique"><strong>Entry/exit technique</strong></h4>
<p>Every minutes, parameter “spread.name” type 1 or 2 based value used as signal, parameter “volat.sd” used to define rolling standard deviation of signal and finally multipled with +/- parameter “m” to get the upper and lower limit. If signal crosses the upper limit we go short and vice versa as mean reverting is applied.</p>
</section>
<section id="strategy-performance" class="level4">
<h4 class="anchored" data-anchor-id="strategy-performance"><strong>Strategy performance</strong></h4>
<p>Below graph represent net vs gross pnl for out of sample 2024 Q4.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/g1_q4_2024.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">g1_q4_2024</figcaption>
</figure>
</div>
</section>
</section>
<section id="group-1---2022-2024-quarterly-results-in-sample-data" class="level3">
<h3 class="anchored" data-anchor-id="group-1---2022-2024-quarterly-results-in-sample-data">Group 1 - 2022-2024 quarterly results (In sample data)</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">X</th>
<th style="text-align: left;">Quarter.Name</th>
<th style="text-align: right;">Gross.SR</th>
<th style="text-align: right;">Net.SR</th>
<th style="text-align: right;">Gross.CR</th>
<th style="text-align: right;">Net.CR</th>
<th style="text-align: right;">Gross.cumP.L</th>
<th style="text-align: right;">Net.cumP.L</th>
<th style="text-align: right;">Av.ntrades</th>
<th style="text-align: right;">Stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">2022_Q1</td>
<td style="text-align: right;">-0.0544624</td>
<td style="text-align: right;">-1.3356356</td>
<td style="text-align: right;">-0.1013886</td>
<td style="text-align: right;">-1.978188</td>
<td style="text-align: right;">-577.280</td>
<td style="text-align: right;">-14452.735</td>
<td style="text-align: right;">4.644068</td>
<td style="text-align: right;">-5.283512</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">2022_Q3</td>
<td style="text-align: right;">-0.2735316</td>
<td style="text-align: right;">-0.8866143</td>
<td style="text-align: right;">-0.5287689</td>
<td style="text-align: right;">-1.530431</td>
<td style="text-align: right;">-2837.795</td>
<td style="text-align: right;">-9247.564</td>
<td style="text-align: right;">2.166667</td>
<td style="text-align: right;">-3.404230</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">2022_Q4</td>
<td style="text-align: right;">3.7798816</td>
<td style="text-align: right;">2.5726020</td>
<td style="text-align: right;">12.4474066</td>
<td style="text-align: right;">7.098790</td>
<td style="text-align: right;">22419.653</td>
<td style="text-align: right;">14865.495</td>
<td style="text-align: right;">2.666667</td>
<td style="text-align: right;">19.159937</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">2023_Q2</td>
<td style="text-align: right;">6.9713478</td>
<td style="text-align: right;">5.2925002</td>
<td style="text-align: right;">44.5676697</td>
<td style="text-align: right;">27.486047</td>
<td style="text-align: right;">53970.728</td>
<td style="text-align: right;">40750.735</td>
<td style="text-align: right;">4.300000</td>
<td style="text-align: right;">101.903802</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">2023_Q4</td>
<td style="text-align: right;">4.2290601</td>
<td style="text-align: right;">2.8969007</td>
<td style="text-align: right;">27.1422746</td>
<td style="text-align: right;">14.412131</td>
<td style="text-align: right;">22088.172</td>
<td style="text-align: right;">14856.988</td>
<td style="text-align: right;">2.271186</td>
<td style="text-align: right;">38.890707</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">2024_Q1</td>
<td style="text-align: right;">2.5614741</td>
<td style="text-align: right;">0.8205267</td>
<td style="text-align: right;">4.8902179</td>
<td style="text-align: right;">1.070790</td>
<td style="text-align: right;">12773.703</td>
<td style="text-align: right;">3430.214</td>
<td style="text-align: right;">2.866667</td>
<td style="text-align: right;">1.319879</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">2024_Q2</td>
<td style="text-align: right;">0.8397483</td>
<td style="text-align: right;">-0.8141622</td>
<td style="text-align: right;">2.2668195</td>
<td style="text-align: right;">-1.552525</td>
<td style="text-align: right;">4840.637</td>
<td style="text-align: right;">-4716.803</td>
<td style="text-align: right;">2.933333</td>
<td style="text-align: right;">-2.408170</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="group-1---2022-2024-quarterly-results-out-sample-data" class="level3">
<h3 class="anchored" data-anchor-id="group-1---2022-2024-quarterly-results-out-sample-data">Group 1 - 2022-2024 quarterly results (Out sample data)</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">X</th>
<th style="text-align: left;">Quarter.Name</th>
<th style="text-align: right;">Gross.SR</th>
<th style="text-align: right;">Net.SR</th>
<th style="text-align: right;">Gross.CR</th>
<th style="text-align: right;">Net.CR</th>
<th style="text-align: right;">Gross.cumP.L</th>
<th style="text-align: right;">Net.cumP.L</th>
<th style="text-align: right;">Av.ntrades</th>
<th style="text-align: right;">Stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">2022_Q2</td>
<td style="text-align: right;">3.786966</td>
<td style="text-align: right;">3.221686</td>
<td style="text-align: right;">13.739149</td>
<td style="text-align: right;">11.514675</td>
<td style="text-align: right;">37695.061</td>
<td style="text-align: right;">32126.32</td>
<td style="text-align: right;">1.932203</td>
<td style="text-align: right;">39.952187</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">2023_Q1</td>
<td style="text-align: right;">-0.924567</td>
<td style="text-align: right;">-1.937151</td>
<td style="text-align: right;">-1.647921</td>
<td style="text-align: right;">-2.635071</td>
<td style="text-align: right;">-6691.361</td>
<td style="text-align: right;">-13934.36</td>
<td style="text-align: right;">2.483333</td>
<td style="text-align: right;">-6.941720</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">2023_Q3</td>
<td style="text-align: right;">-2.309336</td>
<td style="text-align: right;">-4.301788</td>
<td style="text-align: right;">-3.232991</td>
<td style="text-align: right;">-3.877103</td>
<td style="text-align: right;">-15872.490</td>
<td style="text-align: right;">-28903.23</td>
<td style="text-align: right;">4.100000</td>
<td style="text-align: right;">-13.042394</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">2024_Q3</td>
<td style="text-align: right;">2.908354</td>
<td style="text-align: right;">2.192217</td>
<td style="text-align: right;">15.945108</td>
<td style="text-align: right;">10.916840</td>
<td style="text-align: right;">25111.430</td>
<td style="text-align: right;">18954.20</td>
<td style="text-align: right;">1.868853</td>
<td style="text-align: right;">32.117622</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">2024_Q4</td>
<td style="text-align: right;">2.431699</td>
<td style="text-align: right;">1.151158</td>
<td style="text-align: right;">8.872391</td>
<td style="text-align: right;">2.782567</td>
<td style="text-align: right;">17241.929</td>
<td style="text-align: right;">8063.59</td>
<td style="text-align: right;">2.754098</td>
<td style="text-align: right;">5.808217</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="approaches-undertaken" class="level2">
<h2 class="anchored" data-anchor-id="approaches-undertaken">Approaches undertaken</h2>
<section id="group-2" class="level3">
<h3 class="anchored" data-anchor-id="group-2">Group 2</h3>
</section>
</section>
<section id="assumptions-1" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-1">Assumptions:</h2>
<ul>
<li><p>Don’t use the data in (9:31 - 9:40) and (15:51 - 16:00)</p></li>
<li><p>LEAVE ALL POSITIONS before the break starts (16:45 - 18:15). In order to have less volatility we leave 15 minutes not 10 minutes.</p></li>
<li><p>Ignore weekends positions since the market is closed (Fri, 16:00 - Sun, 18:00)</p></li>
</ul>
<p>We used the different strategies including and excluding some assets. First of all, we tried based on pair trading using average closing price spread and standard deviation of returns based on spread dividing pairs by currencies(CAD&amp;AUD) and metals(XAU&amp;XAG). The results were not satisfactory.</p>
<p>Secondly, we used mean-reversion volatility breakout strategy using AUD and pair of commodities XAU&amp;XAG. In AUD, we found best strategy using intersection of fast 30 SMA and 90 slow SMA and 100 volatility memory as a breakout and also multiplier of 1.25. In XAU&amp;XAG, we used spread = XAU - XAG * mean (XAU/XAG) with parameters as 120 window standard deviation and 0.9 upper and lower threshold multipliers.</p>
<p>CAD has similar patterns with AUD but cointegration between these two assets was detected rarely, so It made it useless to probe a new strategy using these currencies. That is why we dropped CAD in our strategy in order to minimize the risk.</p>
<section id="group-2--2022-first-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2--2022-first-quarter-results">Group 2- 2022 first quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><pre><code>-0.08796367</code></pre></td>
<td><pre><code>-0.3203243</code></pre></td>
<td><pre><code>-0.1287973</code></pre></td>
<td><pre><code>-0.4405723</code></pre></td>
<td><pre><code>-59418.29</code></pre></td>
<td><pre><code>-215532.6</code></pre></td>
<td><pre><code>4.611111</code></pre></td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2022_Q1plot.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">g2_q1_2022</figcaption>
</figure>
</div>
<p>In the first quarter of 2022, our strategy concluded with negative PnL due to high volatility and Its stat value is -2.3672.</p>
</section>
<section id="group-2---2022-third-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2---2022-third-quarter-results">Group 2 - 2022 third quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><pre><code>1.00793395</code></pre></td>
<td><pre><code>0.7994004</code></pre></td>
<td><pre><code> 2.2682883</code></pre></td>
<td><pre><code>1.6832033</code></pre></td>
<td><pre><code>838372.21</code></pre></td>
<td><pre><code>661778.9</code></pre></td>
<td><pre><code>4.763441</code></pre></td>
</tr>
</tbody>
</table>
<p><img src="images/2022_Q3plot.png" class="img-fluid" alt="g2_q3_2022"> In the third quarter of 2022, our strategy concluded with profit and Its stat value is 10,9323.</p>
</section>
<section id="group-2---2022-fourth-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2---2022-fourth-quarter-results">Group 2 - 2022 fourth quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><pre><code>-0.28367666</code></pre></td>
<td><pre><code>-0.4872866</code></pre></td>
<td><pre><code>-0.5528670</code></pre></td>
<td><pre><code>-0.9162963</code></pre></td>
<td><pre><code>-238877.84</code></pre></td>
<td><pre><code>-408326.5</code></pre></td>
<td><pre><code>4.901099</code></pre></td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2022_Q4plot.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">g2_q4_2022</figcaption>
</figure>
</div>
<p>In the 4th quarter of 2022, our strategy was unsuccesfull, so Its stat value is -5.5088.</p>
</section>
<section id="group-2---2023-second-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2---2023-second-quarter-results">Group 2 - 2023 Second quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.8115</td>
<td>1.5756</td>
<td>4.3407</td>
<td>3.6753</td>
<td>1243477.0309</td>
<td>1070183.7479</td>
<td>5.1556</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2023_Q2plot.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">g2_q2_2023</figcaption>
</figure>
</div>
<p>In the second quarter of 2023, our stratgey concluded with success and its stat value 25.6372.</p>
</section>
<section id="group-2---2023-fourth-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2---2023-fourth-quarter-results">Group 2 - 2023 Fourth quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.4194</td>
<td>0.1852</td>
<td>0.9724</td>
<td>0.4112</td>
<td>323969.7207</td>
<td>142276.2714</td>
<td>5.0444</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2023_Q4plot.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">g2_q4_2023</figcaption>
</figure>
</div>
<p>In the fiurth quarter of 2023, our strategy was successfull with 2.0388 stat value.</p>
</section>
<section id="group-2---2024-first-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2---2024-first-quarter-results">Group 2 - 2024 First quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-0.1721</td>
<td>-0.4597</td>
<td>-0.4496</td>
<td>-1.0528</td>
<td>-103307.4365</td>
<td>-274562.6246</td>
<td>4.6957</td>
</tr>
</tbody>
</table>
<p><img src="images/2024_Q1plot.png" class="img-fluid" alt="g2_q1_2024"> In the first quarter of 2024, our strategy concluded with negative PnL and Its stat value is -5,9118.</p>
</section>
<section id="group-2---2024-second-quarter-results" class="level3">
<h3 class="anchored" data-anchor-id="group-2---2024-second-quarter-results">Group 2 - 2024 Second quarter results</h3>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>gross SR</th>
<th>net SR</th>
<th>gross CR</th>
<th>net CR</th>
<th>gross cumP&amp;L</th>
<th>net cumP&amp;L</th>
<th>av.ntrades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.1043</td>
<td>0.98689</td>
<td>1.8792</td>
<td>1.662</td>
<td>1670146.1874</td>
<td>1487773.1757</td>
<td>5.0326</td>
</tr>
</tbody>
</table>
<p><img src="images/2024_Q2plot.png" class="img-fluid" alt="g2_q2_2024"> In the second quarter of 2024, our strategy concluded with positive PnL and Its stat value is 12.1413.</p>
</section>
</section>
<section id="group-2---2022-2024-quarterly-results" class="level2">
<h2 class="anchored" data-anchor-id="group-2---2022-2024-quarterly-results">Group 2 - 2022-2024 quarterly results</h2>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">quarter</th>
<th style="text-align: right;">assets.group</th>
<th style="text-align: right;">grossSR</th>
<th style="text-align: right;">netSR</th>
<th style="text-align: right;">grossCR</th>
<th style="text-align: right;">netCR</th>
<th style="text-align: right;">av.daily.ntrades</th>
<th style="text-align: right;">grossPnL</th>
<th style="text-align: right;">netPnL</th>
<th style="text-align: right;">stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2022_Q1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-0.0880</td>
<td style="text-align: right;">-0.3203</td>
<td style="text-align: right;">-0.1288</td>
<td style="text-align: right;">-0.4406</td>
<td style="text-align: right;">4.6111</td>
<td style="text-align: right;">-59418.29</td>
<td style="text-align: right;">-215532.6</td>
<td style="text-align: right;">-2.3672</td>
</tr>
<tr class="even">
<td style="text-align: left;">2022_Q3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.0079</td>
<td style="text-align: right;">0.7994</td>
<td style="text-align: right;">2.2683</td>
<td style="text-align: right;">1.6832</td>
<td style="text-align: right;">4.7634</td>
<td style="text-align: right;">838372.21</td>
<td style="text-align: right;">661778.9</td>
<td style="text-align: right;">10.9323</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022_Q4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-0.2837</td>
<td style="text-align: right;">-0.4873</td>
<td style="text-align: right;">-0.5529</td>
<td style="text-align: right;">-0.9163</td>
<td style="text-align: right;">4.9011</td>
<td style="text-align: right;">-238877.84</td>
<td style="text-align: right;">-408326.5</td>
<td style="text-align: right;">-5.5088</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023_Q2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.8185</td>
<td style="text-align: right;">1.5756</td>
<td style="text-align: right;">4.3407</td>
<td style="text-align: right;">3.6753</td>
<td style="text-align: right;">5.1556</td>
<td style="text-align: right;">1243477.03</td>
<td style="text-align: right;">1070183.7</td>
<td style="text-align: right;">25.6372</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2023_Q4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.4194</td>
<td style="text-align: right;">0.1852</td>
<td style="text-align: right;">0.9724</td>
<td style="text-align: right;">0.4112</td>
<td style="text-align: right;">5.0440</td>
<td style="text-align: right;">323969.72</td>
<td style="text-align: right;">142276.3</td>
<td style="text-align: right;">2.0388</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024_Q1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-0.1721</td>
<td style="text-align: right;">-0.4597</td>
<td style="text-align: right;">-0.4496</td>
<td style="text-align: right;">-1.0528</td>
<td style="text-align: right;">4.6957</td>
<td style="text-align: right;">-103307.44</td>
<td style="text-align: right;">-274562.6</td>
<td style="text-align: right;">-5.9118</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024_Q2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.1043</td>
<td style="text-align: right;">0.9869</td>
<td style="text-align: right;">1.8792</td>
<td style="text-align: right;">1.6620</td>
<td style="text-align: right;">5.0326</td>
<td style="text-align: right;">1670146.19</td>
<td style="text-align: right;">1487773.2</td>
<td style="text-align: right;">12.1413</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="group-2---out-of-sample-data-strategy-checking" class="level1">
<h1>Group 2 - out of sample data, strategy checking</h1>
<p>In our strategy, we used mean-reversion volatility breakout strategy using AUD and pair of commodities XAU&amp;XAG. In AUD, we found best strategy using intersection of fast 30 SMA and 90 slow SMA and 100 volatility memory as a breakout and also multiplier of 1.25. In XAU&amp;XAG, we used spread = XAU - XAG * mean (XAU/XAG) with parameters as 120 window standard deviation with 0.9 upper and lower threshold multipliers.</p>
<p>CAD has similar patterns with AUD but cointegration between these two assets was detected rarely, so It made it useless to probe a new strategy using these currencies. That is why we dropped CAD in our strategy in order to minimize the risk. In our sample, we got 4 positive and 3 negative PnL, which made it actually high risky profitable strategy.</p>
<p>In out of sample data, we evaluated our strategy in 5 quarters and 2 quarter PnL resulted negatively and 3 quarters resulted positvely.</p>
<section id="goup-2---2022-second-quarter-results" class="level2">
<h2 class="anchored" data-anchor-id="goup-2---2022-second-quarter-results">Goup 2 - 2022 second quarter results</h2>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>grossSR</th>
<th>netSR</th>
<th>grossCR</th>
<th>netCR</th>
<th>av_daily_ntrades</th>
<th>grossPnL</th>
<th>netPnL</th>
<th>stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.4568</td>
<td>1.2215</td>
<td>2.9196</td>
<td>2.3933</td>
<td>4.5543</td>
<td>980965.6977</td>
<td>817158.5127</td>
<td>16.0489</td>
</tr>
</tbody>
</table>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
<p><img src="images/pnl_group2_2022_Q2.png" class="img-fluid"></p>
<p>Strategy performs well, with strong risk-adjusted metrics (Sharpe and Calmar Ratios) and substantial profitability. The graph clearly demonstrates a consistent upward trajectory for both gross and net PnL, with close alignment indicating efficient trade execution and manageable costs. While there are some drawdowns (notably mid-May), the recovery is swift, reflecting the profit.</p>
</section>
<section id="group-2---2023-first-quarter-results" class="level2">
<h2 class="anchored" data-anchor-id="group-2---2023-first-quarter-results">Group 2 - 2023 first quarter results</h2>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>grossSR</th>
<th>netSR</th>
<th>grossCR</th>
<th>netCR</th>
<th>av_daily_ntrades</th>
<th>grossPnL</th>
<th>netPnL</th>
<th>stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-0.0603</td>
<td>-0.2962</td>
<td>-0.1019</td>
<td>-0.4712</td>
<td>5.2197</td>
<td>-487751.5231</td>
<td>-238117.2248</td>
<td>-2.5788</td>
</tr>
</tbody>
</table>
<p><img src="images/pnl_group2_2023_Q1.png" class="img-fluid"></p>
<p>The strategy performed poorly during Q1 2023, as indicated by negative metrics across Sharpe Ratio, Calmar Ratio, and PnL. The graph sustains losses, significant drawdowns, and only minimal recoveries. The increased number of trades (higher daily activity) contribute to inefficiency, increasing costs and eroding profitability as a result.</p>
</section>
<section id="group-2---2023-third-quarter" class="level2">
<h2 class="anchored" data-anchor-id="group-2---2023-third-quarter">Group 2 - 2023 third quarter</h2>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>grossSR</th>
<th>netSR</th>
<th>grossCR</th>
<th>netCR</th>
<th>av_daily_ntrades</th>
<th>grossPnL</th>
<th>netPnL</th>
<th>stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.5604</td>
<td>0.2986</td>
<td>0.7815</td>
<td>0.4037</td>
<td>4.9670</td>
<td>372440.7214</td>
<td>197466.0342</td>
<td>2.1034</td>
</tr>
</tbody>
</table>
<p><img src="images/pnl_group2_2023_Q3.png" class="img-fluid"></p>
<p>The graph shows strong upward trends in July and late September, with significant drawdowns in late August and early September. The Sharpe Ratio (gross: 0.5604, net: 0.2986) reflects modest risk-adjusted returns, with some impact from costs. Similarly, the Calmar Ratio (gross: 0.7815, net: 0.4037) indicates moderate recovery, though costs slightly hinder overall performance.</p>
</section>
<section id="group-2---2024-third-quarter" class="level2">
<h2 class="anchored" data-anchor-id="group-2---2024-third-quarter">Group 2 - 2024 third quarter</h2>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>grossSR</th>
<th>netSR</th>
<th>grossCR</th>
<th>netCR</th>
<th>av_daily_ntrades</th>
<th>grossPnL</th>
<th>netPnL</th>
<th>stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-1.1797</td>
<td>-1.3948</td>
<td>-1.5367</td>
<td>-2.4594</td>
<td>4.5483</td>
<td>-1325203.9319</td>
<td>-1407277.3191</td>
<td>-11.9321</td>
</tr>
</tbody>
</table>
<p><img src="images/pnl_group2_2024_Q3.png" class="img-fluid"></p>
<p>The graph shows a downward trend overall, with minor recoveries in mid-July and late August, followed by steep declines in early September and late September. The Sharpe Ratio (gross: -1.1797, net: -1.3948) indicates negative risk-adjusted returns, suggesting the strategy consistently underperformed relative to its volatility. The Calmar Ratio (gross: -1.5367, net: -2.4594) further reflects significant drawdowns and poor recovery ability.</p>
</section>
<section id="group-2---2024-fourth-quarter" class="level2">
<h2 class="anchored" data-anchor-id="group-2---2024-fourth-quarter">Group 2 - 2024 fourth quarter</h2>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>grossSR</th>
<th>netSR</th>
<th>grossCR</th>
<th>netCR</th>
<th>av_daily_ntrades</th>
<th>grossPnL</th>
<th>netPnL</th>
<th>stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.3820</td>
<td>0.2320</td>
<td>0.7983</td>
<td>0.4646</td>
<td>4.2903</td>
<td>383461.0424</td>
<td>232221.0142</td>
<td>2.5308</td>
</tr>
</tbody>
</table>
<p><img src="images/pnl_group2_2024_Q4.png" class="img-fluid"></p>
<p>The graph for Q4 2024 shows a significant improvement in performance compared to the previous quarter, with steady growth overall and recovery from drawdowns. Peaks are evident in late November and late December, while drawdowns occur around mid-October and early December. The Sharpe Ratio (gross: 0.3820, net: 0.2320) reflects modest but positive risk-adjusted returns, indicating improved profitability relative to volatility. The Calmar Ratio (gross: 0.7983, net: 0.4646) highlights better drawdown recovery and resilience.</p>
</section>
<section id="group-2---summary" class="level2">
<h2 class="anchored" data-anchor-id="group-2---summary">Group 2 - Summary</h2>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>quarter</th>
<th>grossSR</th>
<th>netSR</th>
<th>grossCR</th>
<th>netCR</th>
<th>av_daily_ntrades</th>
<th>grossPnL</th>
<th>netPnL</th>
<th>stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2022_Q2</td>
<td>1.4568</td>
<td>1.2215</td>
<td>2.9196</td>
<td>2.3933</td>
<td>4.5543</td>
<td>980965.6977</td>
<td>817158.5127</td>
<td>16.0489</td>
</tr>
<tr class="even">
<td>2023_Q1</td>
<td>-0.0603</td>
<td>-0.2962</td>
<td>-0.1019</td>
<td>-0.4712</td>
<td>5.2197</td>
<td>-487751.5231</td>
<td>-238117.2248</td>
<td>-2.5788</td>
</tr>
<tr class="odd">
<td>2023_Q3</td>
<td>0.5604</td>
<td>0.2986</td>
<td>0.7815</td>
<td>0.4037</td>
<td>4.9670</td>
<td>372440.7214</td>
<td>197466.0342</td>
<td>2.1034</td>
</tr>
<tr class="even">
<td>2024_Q3</td>
<td>-1.1797</td>
<td>-1.3948</td>
<td>-1.5367</td>
<td>-2.4594</td>
<td>4.5483</td>
<td>-1325203.9319</td>
<td>-1407277.3191</td>
<td>-11.9321</td>
</tr>
<tr class="odd">
<td>2024_Q4</td>
<td>0.3820</td>
<td>0.2320</td>
<td>0.7983</td>
<td>0.4646</td>
<td>4.2903</td>
<td>383461.0424</td>
<td>232221.0142</td>
<td>2.5308</td>
</tr>
</tbody>
</table>
<p>The strategy shows strong potential in favorable quarters, such as the second quarters of 2022 and 2023, 2024 with high risk-adjusted returns and effective recovery from drawdowns, indicating consistent profitability and efficient cost management. However, it suffers from significant underperformance in challenging periods, like the third quarter of 2024, where large drawdowns and poor recovery heavily impacted profitability. Morever, sign of gross and net PnL and number of transaction in all quarters shows that all loss is contributed by stategy performance not high transaction cost.</p>
<p>The fluctuations reveal a high sensitivity to market conditions, suggesting that the strategy may depend on specific dynamics for success.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="presentation_hft_2025_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>